# Picom v13

backend = "glx";
vsync = true;
use-damage = true;
unredir-if-possible = false;


# ─────────────────────────────
# Fading
# ─────────────────────────────

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 6;


# ─────────────────────────────
# Shadows
# ─────────────────────────────

shadow = true;
shadow-radius = 16;
shadow-offset-x = -6;
shadow-offset-y = -6;
shadow-opacity = 0.12;


# ─────────────────────────────
# Blur
# ─────────────────────────────

blur: {
    method = "dual_kawase";
    strength = 3;

    background = true;
    background-frame = false;
    background-fixed = false;
};


# ─────────────────────────────
# Rules
# ─────────────────────────────

rules = (

    # Desktop / panels / GTK decorations
    {
        match = "window_type = 'desktop' || window_type = 'dock' || _GTK_FRAME_EXTENTS@";

        shadow = false;
        blur-background = false;
        corner-radius = 0;
    },

    # Normal windows
    {
        match = "window_type = 'normal'";

        corner-radius = 12;

        shadow = true;
        shadow-radius = 16;
        shadow-offset-x = -6;
        shadow-offset-y = -6;
        shadow-opacity = 0.12;

        blur-background = true;
    },

    # Tooltips
    {
        match = "window_type = 'tooltip'";

        fade = true;
        opacity = 0.95;

        shadow = false;
        blur-background = false;

        corner-radius = 6;
    },

    # Popup menus
    {
        match = "window_type = 'popup_menu' || window_type = 'dropdown_menu'";

        opacity = 0.98;

        shadow = false;
        blur-background = false;

        corner-radius = 6;
    },

    # Notifications
    {
        match = "window_type = 'notification'";

        shadow = true;
        shadow-radius = 12;
        shadow-opacity = 0.12;

        blur-background = false;
        corner-radius = 8;
    },

    # Drag & drop windows
    {
        match = "window_type = 'dnd'";

        shadow = false;
        blur-background = false;

        corner-radius = 6;
    }
);