########################################
# polybar @yojeero - Kanagawa Theme
# https://coolors.co/fdfdfd/variations
########################################

# transparents - insert before color
# 10% — 1A
# 20% — 33
# 30% — 4D
# 40% — 66
# 50% — 80
# 60% — 99
# 70% — B3
# 80% — CC
# 90% — E6

[colors]

background = #801f1f28
foreground = #dcd7ba
space = #5E5C64
accent = #9A9996
red = #FB607F
purple = #BCBCED
blue = #7dc4e4
orange = #ffc300
green = #71D044

[bar/top]

width = 70%
height = 40

radius = 0.0
radius-bottom = 12.0
radius-bottom-left = 12.0
radius-bottom-right = 12.0
radius-top-left = 0.0
radius-top-right = 0.0

background = ${colors.background}
foreground = ${colors.foreground}

offset-x = 15%
offset-y = 0

padding-left = 4
padding-right = 4

fixed-center = true
monitor-strict = false

modules-left = rofi hlwm-tag
modules-center = date
modules-right = xkeyboard space pulseaudio space wlan ethernet space powermenu

font-0 = "Terminess Nerd Font:size=12;2"
font-1 = "Symbols Nerd Font Mono:size=9;2"

enable-ipc = true
override-redirect = true

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; modules
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/rofi]

type = custom/text

format = " "
format-padding = 1
format-font = 2
format-foreground = ${colors.red}

click-left = rofi -show drun
click-right = rofi -no-grab -show drun

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/hlwm-tag]

type = custom/script

exec = ~/.config/polybar/hlwm-polybar/hlwm-tags.sh
tail = true

format = <label>
format-padding = 1

scroll-up = herbstclient use_index +1
scroll-down = herbstclient use_index -1


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/date]

type = internal/date

interval = 1.0

date = "%H:%M  -  %a, %d %b"

format = <label>
format-prefix = "  "
format-prefix-foreground = ${colors.blue}
format-font = 2

label = %date%
label-foreground = ${colors.foreground}
label-font = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/xkeyboard]

type = internal/xkeyboard

format = <label-layout> <label-indicator>
format-prefix = "  "
format-prefix-foreground = ${colors.blue}
format-font = 2

label-layout-foreground = ${colors.foreground}
label-font = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/pulseaudio]

type = internal/pulseaudio

format-volume = <label-volume>
format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.green}
format-volume-font = 2

label-volume = %percentage%%
label-volume-foreground = ${colors.foreground}
label-font = 1

label-muted = "  "
label-muted-foreground = ${colors.red}
label-muted-font = 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/wlan]

type = internal/network

interface-type = wireless

format-connected = <label-connected>
format-disconnected = <label-disconnected>

format-connected-font = 2
format-disconnected-font = 2

label-connected = "  %essid%"
label-connected-foreground = ${colors.foreground}

label-disconnected = "  offline"
label-disconnected-foreground = ${colors.foreground}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/ethernet]

type = internal/network

interface = enp8s0
interface-type = wired

format-connected = <label-connected>
format-disconnected = <label-disconnected>

format-connected-font = 2
format-disconnected-font = 2

label-connected = " 󰌘 "
label-connected-foreground = ${colors.orange}

label-disconnected = " 󰌙 "
label-disconnected-foreground = ${colors.red}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/powermenu]

type = custom/text

format = 
format-font = 2
format-foreground = ${colors.purple}

click-left = rofi -modi "power:$HOME/.config/rofi/power.sh" -show power -theme $HOME/.config/rofi/powermenu.rasi

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/space]

type = custom/text

format = "/"
format-padding = 1
format-foreground = ${colors.space}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[settings]

screenchange-reload = true
pseudo-transparency = true